# Recipe-specific configuration
# Add any custom configuration options your recipe needs here.
assistantId = '' # fill in with your watsonx Assistant ID
environmentId = '' # fill in with your watsonx Assistant environment ID

# Customization 1: Change the likelihood that TJBot follows an instruction
# when "Simon Says" wasn't said (range: [0.0, 1.0])
followLikelihood = 0.2
